services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "AfraAppUser"
      POSTGRES_PASSWORD: "AfraAppPassword"
      POSTGRES_DB: "afra-app"
  mailcatcher:
    build:
      context: mock-smtp-server
      dockerfile: Dockerfile
    ports:
      - "8090:1080"
      - "1025:1025"
