services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "AfraAppUser"
      POSTGRES_PASSWORD: "AfraAppPassword"
      POSTGRES_DB: "afra-app"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  mailcatcher:
    build:
      context: mock-smtp-server
      dockerfile: Dockerfile
    ports:
      - "8090:1080"
      - "1025:1025"
  emergency:
    build: ./emergency
    environment:
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=admin
      - FILE_DIR=/data
      - RETENTION_SECONDS=86400
      - SWEEP_INTERVAL_SECONDS=60
    volumes:
      - ./emergency-data:/data
    ports:
      - "8000:8000"
