// <auto-generated />
using System;
using System.Collections.Generic;
using Altafraner.AfraApp;
using Altafraner.AfraApp.Otium.Domain.Models;
using Altafraner.AfraApp.Schuljahr.Domain.Models;
using Altafraner.AfraApp.User.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altafraner.AfraApp.Migrations
{
    [DbContext(typeof(AfraAppContext))]
    [Migration("20251228185843_AllColumnsLowerCase")]
    partial class AllColumnsLowerCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "anwesenheits_status", new[] { "anwesend", "entschuldigt", "fehlend" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "global_permission", new[] { "admin", "otiumsverantwortlich", "profundumsverantwortlich" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "person_rolle", new[] { "mittelstufe", "oberstufe", "tutor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wochentyp", new[] { "h", "n" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altafraner.AfraApp.Calendar.Domain.Models.CalendarSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffenepersonid");

                    b.HasKey("Id")
                        .HasName("pk_calendarsubscriptions");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_calendarsubscriptions_betroffenepersonid");

                    b.ToTable("calendarsubscriptions");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheit", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("blockid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.Property<OtiumAnwesenheitsStatus>("Status")
                        .HasColumnType("anwesenheits_status")
                        .HasColumnName("status");

                    b.HasKey("BlockId", "StudentId")
                        .HasName("pk_otiaanwesenheiten");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_otiaanwesenheiten_studentid");

                    b.ToTable("otiaanwesenheiten");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheitsNotiz", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("blockid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.HasKey("BlockId", "StudentId", "AuthorId")
                        .HasName("pk_otiaeinschreibungsnotizen");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_otiaeinschreibungsnotizen_authorid");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_otiaeinschreibungsnotizen_studentid");

                    b.ToTable("otiaeinschreibungsnotizen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("beschreibung");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("kategorieid");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<int?>("MaxKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("maxklasse");

                    b.Property<int?>("MinKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("minklasse");

                    b.HasKey("Id")
                        .HasName("pk_otia");

                    b.HasIndex("KategorieId")
                        .HasDatabaseName("ix_otia_kategorieid");

                    b.ToTable("otia");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffenepersonid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<Guid>("TerminId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Interval", "Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung.Interval#TimeOnlyInterval", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id")
                        .HasName("pk_otiaeinschreibungen");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_otiaeinschreibungen_betroffenepersonid");

                    b.HasIndex("TerminId")
                        .HasDatabaseName("ix_otiaeinschreibungen_terminid");

                    b.ToTable("otiaeinschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bezeichnung");

                    b.Property<string>("CssColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("csscolor");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon");

                    b.Property<bool>("IgnoreEnrollmentRule")
                        .HasColumnType("boolean")
                        .HasColumnName("ignoreenrollmentrule");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.HasKey("Id")
                        .HasName("pk_otiakategorien");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_otiakategorien_parentid");

                    b.ToTable("otiakategorien");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("blockid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IstAbgesagt")
                        .HasColumnType("boolean")
                        .HasColumnName("istabgesagt");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("maxeinschreibungen");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ort");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("otiumid");

                    b.Property<string>("OverrideBeschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("overridebeschreibung");

                    b.Property<string>("OverrideBezeichnung")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("overridebezeichnung");

                    b.Property<bool>("SindAnwesenheitenKontrolliert")
                        .HasColumnType("boolean")
                        .HasColumnName("sindanwesenheitenkontrolliert");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorid");

                    b.Property<Guid?>("WiederholungId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiederholungid");

                    b.HasKey("Id")
                        .HasName("pk_otiatermine");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_otiatermine_blockid");

                    b.HasIndex("OtiumId")
                        .HasDatabaseName("ix_otiatermine_otiumid");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_otiatermine_tutorid");

                    b.HasIndex("WiederholungId")
                        .HasDatabaseName("ix_otiatermine_wiederholungid");

                    b.ToTable("otiatermine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<char>("Block")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasColumnName("block")
                        .HasDefaultValueSql("''");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("maxeinschreibungen");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ort");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("otiumid");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorid");

                    b.Property<int>("Wochentag")
                        .HasColumnType("integer")
                        .HasColumnName("wochentag");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp")
                        .HasColumnName("wochentyp");

                    b.HasKey("Id")
                        .HasName("pk_otiawiederholungen");

                    b.HasIndex("OtiumId")
                        .HasDatabaseName("ix_otiawiederholungen_otiumid");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_otiawiederholungen_tutorid");

                    b.ToTable("otiawiederholungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumBelegWunsch", b =>
                {
                    b.Property<Guid>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profunduminstanzid");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffenepersonid");

                    b.Property<int>("Stufe")
                        .HasColumnType("integer")
                        .HasColumnName("stufe");

                    b.HasKey("ProfundumInstanzId", "BetroffenePersonId", "Stufe")
                        .HasName("pk_profundabelegwuensche");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_profundabelegwuensche_betroffenepersonid");

                    b.ToTable("profundabelegwuensche");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bezeichnung");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("kategorieid");

                    b.Property<int?>("MaxKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("maxklasse");

                    b.Property<int?>("MinKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("minklasse");

                    b.HasKey("Id")
                        .HasName("pk_profunda");

                    b.HasIndex("KategorieId")
                        .HasDatabaseName("ix_profunda_kategorieid");

                    b.ToTable("profunda");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinschreibung", b =>
                {
                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffenepersonid");

                    b.Property<Guid>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profunduminstanzid");

                    b.HasKey("BetroffenePersonId", "ProfundumInstanzId")
                        .HasName("pk_profundaeinschreibungen");

                    b.HasIndex("ProfundumInstanzId")
                        .HasDatabaseName("ix_profundaeinschreibungen_profunduminstanzid");

                    b.ToTable("profundaeinschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EinwahlStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einwahlstart");

                    b.Property<DateTime>("EinwahlStop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einwahlstop");

                    b.Property<bool>("HasBeenMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("hasbeenmatched");

                    b.HasKey("Id")
                        .HasName("pk_profundumeinwahlzeitraeume");

                    b.ToTable("profundumeinwahlzeitraeume");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("maxeinschreibungen");

                    b.Property<Guid>("ProfundumId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundumid");

                    b.HasKey("Id")
                        .HasName("pk_profundainstanzen");

                    b.HasIndex("ProfundumId")
                        .HasDatabaseName("ix_profundainstanzen_profundumid");

                    b.ToTable("profundainstanzen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bezeichnung");

                    b.Property<int?>("MaxProEinwahl")
                        .HasColumnType("integer")
                        .HasColumnName("maxproeinwahl");

                    b.Property<bool>("ProfilProfundum")
                        .HasColumnType("boolean")
                        .HasColumnName("profilprofundum");

                    b.HasKey("Id")
                        .HasName("pk_profundakategorien");

                    b.ToTable("profundakategorien");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EinwahlZeitraumId")
                        .HasColumnType("uuid")
                        .HasColumnName("einwahlzeitraumid");

                    b.Property<int>("Jahr")
                        .HasColumnType("integer")
                        .HasColumnName("jahr");

                    b.Property<int>("Quartal")
                        .HasColumnType("integer")
                        .HasColumnName("quartal");

                    b.Property<int>("Wochentag")
                        .HasColumnType("integer")
                        .HasColumnName("wochentag");

                    b.HasKey("Id")
                        .HasName("pk_profundaslots");

                    b.HasIndex("EinwahlZeitraumId")
                        .HasDatabaseName("ix_profundaslots_einwahlzeitraumid");

                    b.ToTable("profundaslots");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<char>("SchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasColumnName("schemaid")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly>("SchultagKey")
                        .HasColumnType("date")
                        .HasColumnName("schultagkey");

                    b.Property<bool>("SindAnwesenheitenFehlernderKontrolliert")
                        .HasColumnType("boolean")
                        .HasColumnName("sindanwesenheitenfehlernderkontrolliert");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("SchultagKey", "SchemaId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_schultagkey_schemaid");

                    b.ToTable("blocks");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", b =>
                {
                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp")
                        .HasColumnName("wochentyp");

                    b.HasKey("Datum")
                        .HasName("pk_schultage");

                    b.ToTable("schultage");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.MentorMenteeRelation", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentorid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("MentorId", "StudentId")
                        .HasName("pk_mentormenteerelations");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_mentormenteerelations_studentid");

                    b.ToTable("mentormenteerelations");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firstname");

                    b.PrimitiveCollection<GlobalPermission[]>("GlobalPermissions")
                        .IsRequired()
                        .HasColumnType("global_permission[]")
                        .HasColumnName("globalpermissions");

                    b.Property<string>("Gruppe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gruppe");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lastname");

                    b.Property<Guid?>("LdapObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("ldapobjectid");

                    b.Property<DateTime?>("LdapSyncFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ldapsyncfailuretime");

                    b.Property<DateTime?>("LdapSyncTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ldapsynctime");

                    b.Property<Rolle>("Rolle")
                        .HasColumnType("person_rolle")
                        .HasColumnName("rolle");

                    b.HasKey("Id")
                        .HasName("pk_personen");

                    b.ToTable("personen");
                });

            modelBuilder.Entity("Altafraner.Backbone.EmailSchedulingModule.Models.ScheduledEmail<Altafraner.AfraApp.User.Domain.Models.Person>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipientid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_scheduledemails");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_scheduledemails_recipientid");

                    b.ToTable("scheduledemails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendlyname");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_dataprotectionkeys");

                    b.ToTable("dataprotectionkeys");
                });

            modelBuilder.Entity("OtiumDefinitionPerson", b =>
                {
                    b.Property<Guid>("VerantwortlicheId")
                        .HasColumnType("uuid")
                        .HasColumnName("verantwortlicheid");

                    b.Property<Guid>("VerwalteteOtiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("verwalteteotiaid");

                    b.HasKey("VerantwortlicheId", "VerwalteteOtiaId")
                        .HasName("pk_otiumdefinitionperson");

                    b.HasIndex("VerwalteteOtiaId")
                        .HasDatabaseName("ix_otiumdefinitionperson_verwalteteotiaid");

                    b.ToTable("otiumdefinitionperson");
                });

            modelBuilder.Entity("ProfundumInstanzProfundumSlot", b =>
                {
                    b.Property<Guid>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profunduminstanzid");

                    b.Property<Guid>("SlotsId")
                        .HasColumnType("uuid")
                        .HasColumnName("slotsid");

                    b.HasKey("ProfundumInstanzId", "SlotsId")
                        .HasName("pk_profunduminstanzprofundumslot");

                    b.HasIndex("SlotsId")
                        .HasDatabaseName("ix_profunduminstanzprofundumslot_slotsid");

                    b.ToTable("profunduminstanzprofundumslot");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Calendar.Domain.Models.CalendarSubscription", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany()
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendarsubscriptions_personen_betroffenepersonid");

                    b.Navigation("BetroffenePerson");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheit", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaanwesenheiten_blocks_blockid");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaanwesenheiten_personen_studentid");

                    b.Navigation("Block");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheitsNotiz", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaeinschreibungsnotizen_personen_authorid");

                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaeinschreibungsnotizen_blocks_blockid");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaeinschreibungsnotizen_personen_studentid");

                    b.Navigation("Author");

                    b.Navigation("Block");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", "Kategorie")
                        .WithMany("Otia")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_otiakategorien_kategorieid");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("OtiaEinschreibungen")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaeinschreibungen_personen_betroffenepersonid");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", "Termin")
                        .WithMany("Enrollments")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiaeinschreibungen_otiatermine_terminid");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_otiakategorien_otiakategorien_parentid");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiatermine_blocks_blockid");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", "Otium")
                        .WithMany("Termine")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiatermine_otia_otiumid");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .HasConstraintName("fk_otiatermine_personen_tutorid");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", "Wiederholung")
                        .WithMany("Termine")
                        .HasForeignKey("WiederholungId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_otiatermine_otiawiederholungen_wiederholungid");

                    b.Navigation("Block");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");

                    b.Navigation("Wiederholung");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", "Otium")
                        .WithMany("Wiederholungen")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiawiederholungen_otia_otiumid");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .HasConstraintName("fk_otiawiederholungen_personen_tutorid");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumBelegWunsch", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("ProfundaBelegwuensche")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundabelegwuensche_personen_betroffenepersonid");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", "ProfundumInstanz")
                        .WithMany()
                        .HasForeignKey("ProfundumInstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundabelegwuensche_profundainstanzen_profunduminstanzid");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("ProfundumInstanz");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", "Kategorie")
                        .WithMany("Profunda")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_profundakategorien_kategorieid");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinschreibung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("ProfundaEinschreibungen")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundaeinschreibungen_personen_betroffenepersonid");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", "ProfundumInstanz")
                        .WithMany("Einschreibungen")
                        .HasForeignKey("ProfundumInstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundaeinschreibungen_profundainstanzen_profunduminstanzid");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("ProfundumInstanz");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", "Profundum")
                        .WithMany("Instanzen")
                        .HasForeignKey("ProfundumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundainstanzen_profunda_profundumid");

                    b.Navigation("Profundum");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", "EinwahlZeitraum")
                        .WithMany("Slots")
                        .HasForeignKey("EinwahlZeitraumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundaslots_profundumeinwahlzeitraeume_einwahlzeitraumid");

                    b.Navigation("EinwahlZeitraum");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", "Schultag")
                        .WithMany("Blocks")
                        .HasForeignKey("SchultagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_schultage_schultagkey");

                    b.Navigation("Schultag");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.MentorMenteeRelation", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentormenteerelations_personen_mentorid");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentormenteerelations_personen_studentid");
                });

            modelBuilder.Entity("Altafraner.Backbone.EmailSchedulingModule.Models.ScheduledEmail<Altafraner.AfraApp.User.Domain.Models.Person>", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scheduledemails_personen_recipientid");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("OtiumDefinitionPerson", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("VerantwortlicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiumdefinitionperson_personen_verantwortlicheid");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", null)
                        .WithMany()
                        .HasForeignKey("VerwalteteOtiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otiumdefinitionperson_otia_verwalteteotiaid");
                });

            modelBuilder.Entity("ProfundumInstanzProfundumSlot", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", null)
                        .WithMany()
                        .HasForeignKey("ProfundumInstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunduminstanzprofundumslot_profundainstanzen_profundumin~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunduminstanzprofundumslot_profundaslots_slotsid");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.Navigation("Termine");

                    b.Navigation("Wiederholungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Otia");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.Navigation("Instanzen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.Navigation("Einschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", b =>
                {
                    b.Navigation("Profunda");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.Person", b =>
                {
                    b.Navigation("OtiaEinschreibungen");

                    b.Navigation("ProfundaBelegwuensche");

                    b.Navigation("ProfundaEinschreibungen");
                });
#pragma warning restore 612, 618
        }
    }
}
