// <auto-generated />
using System;
using Afra_App;
using Afra_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Afra_App.Migrations
{
    [DbContext(typeof(AfraAppContext))]
    [Migration("20250204193538_AddDataProtection")]
    partial class AddDataProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Afra_App.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Appendix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Afra_App.Models.OstiumInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegularityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OtiumId");

                    b.HasIndex("RegularityId");

                    b.HasIndex("TutorId");

                    b.ToTable("OtiaInstallments");
                });

            modelBuilder.Entity("Afra_App.Models.Otium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCataloged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoryDesignation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoryDesignation");

                    b.ToTable("Otia");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AttendanceVerified")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MayEdit")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("OtiaEnrollments");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumRegularity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OtiumId");

                    b.HasIndex("TutorId");

                    b.ToTable("OtiaRegularities");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumsKategory", b =>
                {
                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Designation");

                    b.ToTable("OtiaKategories");
                });

            modelBuilder.Entity("Afra_App.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("MentorId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Afra_App.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("OtiumPerson", b =>
                {
                    b.Property<Guid>("ManagedOtiaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManagersId")
                        .HasColumnType("TEXT");

                    b.HasKey("ManagedOtiaId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("OtiumPerson");
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PersonRole");
                });

            modelBuilder.Entity("Afra_App.Models.Class", b =>
                {
                    b.HasOne("Afra_App.Models.Person", "Tutor")
                        .WithMany("TutoredClasses")
                        .HasForeignKey("TutorId");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Afra_App.Models.OstiumInstallment", b =>
                {
                    b.HasOne("Afra_App.Models.Otium", "Otium")
                        .WithMany("Installments")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Models.OtiumRegularity", "Regularity")
                        .WithMany("Installments")
                        .HasForeignKey("RegularityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Afra_App.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otium");

                    b.Navigation("Regularity");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Afra_App.Models.Otium", b =>
                {
                    b.HasOne("Afra_App.Models.OtiumsKategory", "Kategory")
                        .WithMany("Otia")
                        .HasForeignKey("KategoryDesignation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategory");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumEnrollment", b =>
                {
                    b.HasOne("Afra_App.Models.OstiumInstallment", "Installment")
                        .WithMany("Enrollments")
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Models.Person", "Student")
                        .WithMany("OtiaEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumRegularity", b =>
                {
                    b.HasOne("Afra_App.Models.Otium", "Otium")
                        .WithMany("Regularities")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otium");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Afra_App.Models.Person", b =>
                {
                    b.HasOne("Afra_App.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("Afra_App.Models.Person", "Mentor")
                        .WithMany("Mentees")
                        .HasForeignKey("MentorId");

                    b.Navigation("Class");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("OtiumPerson", b =>
                {
                    b.HasOne("Afra_App.Models.Otium", null)
                        .WithMany()
                        .HasForeignKey("ManagedOtiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.HasOne("Afra_App.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Afra_App.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Afra_App.Models.OstiumInstallment", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Afra_App.Models.Otium", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("Regularities");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumRegularity", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("Afra_App.Models.OtiumsKategory", b =>
                {
                    b.Navigation("Otia");
                });

            modelBuilder.Entity("Afra_App.Models.Person", b =>
                {
                    b.Navigation("Mentees");

                    b.Navigation("OtiaEnrollments");

                    b.Navigation("TutoredClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
