// <auto-generated />
using System;
using System.Collections.Generic;
using Afra_App.Otium.Domain.Models;
using Afra_App.Otium.Domain.Models.Schuljahr;
using Afra_App.User.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Afra_App.Migrations
{
    [DbContext(typeof(AfraAppContext))]
    [Migration("20250528100851_AddAttendance")]
    partial class AddAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "anwesenheits_status", new[] { "anwesend", "entschuldigt", "fehlend" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "person_rolle", new[] { "mittelstufe", "oberstufe", "tutor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wochentyp", new[] { "h", "n" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Afra_App.Data.Email.ScheduledEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("ScheduledEmails");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Anwesenheit", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<AnwesenheitsStatus>("Status")
                        .HasColumnType("anwesenheits_status");

                    b.HasKey("BlockId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("OtiaAnwesenheiten");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Einschreibung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TerminId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Interval", "Afra_App.Data.Otium.Einschreibung.Interval#TimeOnlyInterval", b1 =>
                        {
                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BetroffenePersonId");

                    b.HasIndex("TerminId");

                    b.ToTable("OtiaEinschreibungen");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Kategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CssColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OtiaKategorien");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Otium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Otia");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Termin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IstAbgesagt")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WiederholungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("OtiumId");

                    b.HasIndex("TutorId");

                    b.HasIndex("WiederholungId");

                    b.ToTable("OtiaTermine");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Wiederholung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Block")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasDefaultValueSql("''");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Wochentag")
                        .HasColumnType("integer");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp");

                    b.HasKey("Id");

                    b.HasIndex("OtiumId");

                    b.HasIndex("TutorId");

                    b.ToTable("OtiaWiederholungen");
                });

            modelBuilder.Entity("Afra_App.Data.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("LdapObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LdapSyncTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Rolle>("Rolle")
                        .HasColumnType("person_rolle");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("Afra_App.Data.Schuljahr.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("SchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly>("SchultagKey")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SchultagKey", "SchemaId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Afra_App.Data.Schuljahr.Schultag", b =>
                {
                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp");

                    b.HasKey("Datum");

                    b.ToTable("Schultage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("OtiumPerson", b =>
                {
                    b.Property<Guid>("VerantwortlicheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerwalteteOtiaId")
                        .HasColumnType("uuid");

                    b.HasKey("VerantwortlicheId", "VerwalteteOtiaId");

                    b.HasIndex("VerwalteteOtiaId");

                    b.ToTable("OtiumPerson");
                });

            modelBuilder.Entity("Afra_App.Data.Email.ScheduledEmail", b =>
                {
                    b.HasOne("Afra_App.Data.People.Person", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Anwesenheit", b =>
                {
                    b.HasOne("Afra_App.Data.Schuljahr.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.People.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Einschreibung", b =>
                {
                    b.HasOne("Afra_App.Data.People.Person", "BetroffenePerson")
                        .WithMany("OtiaEinschreibungen")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.Otium.Termin", "Termin")
                        .WithMany("Enrollments")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BetroffenePerson");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Kategorie", b =>
                {
                    b.HasOne("Afra_App.Data.Otium.Kategorie", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Otium", b =>
                {
                    b.HasOne("Afra_App.Data.Otium.Kategorie", "Kategorie")
                        .WithMany("Otia")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Termin", b =>
                {
                    b.HasOne("Afra_App.Data.Schuljahr.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.Otium.Otium", "Otium")
                        .WithMany("Termine")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.People.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId");

                    b.HasOne("Afra_App.Data.Otium.Wiederholung", "Wiederholung")
                        .WithMany("Termine")
                        .HasForeignKey("WiederholungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Block");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");

                    b.Navigation("Wiederholung");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Wiederholung", b =>
                {
                    b.HasOne("Afra_App.Data.Otium.Otium", "Otium")
                        .WithMany("Wiederholungen")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.People.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Afra_App.Data.People.Person", b =>
                {
                    b.HasOne("Afra_App.Data.People.Person", "Mentor")
                        .WithMany("Mentees")
                        .HasForeignKey("MentorId");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Afra_App.Data.Schuljahr.Block", b =>
                {
                    b.HasOne("Afra_App.Data.Schuljahr.Schultag", "Schultag")
                        .WithMany("Blocks")
                        .HasForeignKey("SchultagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schultag");
                });

            modelBuilder.Entity("OtiumPerson", b =>
                {
                    b.HasOne("Afra_App.Data.People.Person", null)
                        .WithMany()
                        .HasForeignKey("VerantwortlicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afra_App.Data.Otium.Otium", null)
                        .WithMany()
                        .HasForeignKey("VerwalteteOtiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Kategorie", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Otia");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Otium", b =>
                {
                    b.Navigation("Termine");

                    b.Navigation("Wiederholungen");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Termin", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Afra_App.Data.Otium.Wiederholung", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Afra_App.Data.People.Person", b =>
                {
                    b.Navigation("Mentees");

                    b.Navigation("OtiaEinschreibungen");
                });

            modelBuilder.Entity("Afra_App.Data.Schuljahr.Schultag", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
