name: backend

permissions:
  contents: read
  packages: read

on:
  push:
    branches: ["*"]
    paths:
      - ".github/workflows/backend.yml"
      - "Backend/**"
  pull_request:
    branches: ["*"]
    paths:
      - "Backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NuGetPackageSourceCredentials_github_altafraner: Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore Backend/Altafraner.AfraApp/Altafraner.AfraApp.csproj
      - name: Build
        run: dotnet build --no-restore Backend/Altafraner.AfraApp/Altafraner.AfraApp.csproj
